#!/bin/bash

# help-project.sh - Mostrar ayuda de todos los comandos
echo "🆘 AYUDA - AUTOSERVICE LIAM YAHIR"
echo "=================================="
echo ""
echo "🚀 COMANDOS DISPONIBLES:"
echo ""
echo "  ./start-project.sh    - Iniciar TODO el proyecto (frontend + backend)"
echo "  ./stop-project.sh     - Detener todos los procesos"
echo "  ./dev-frontend.sh     - Solo desarrollo frontend"
echo "  ./dev-backend.sh      - Solo desarrollo backend"
echo ""
echo "🛠️  CONFIGURACIÓN:"
echo "  ./setup-project.sh    - Configuración inicial completa"
echo "  ./reset-project.sh    - Limpiar y reinstalar TODO"
echo "  ./check-ports.sh      - Verificar puertos en uso"
echo ""
echo "📊 MONITOREO:"
echo "  ./logs-frontend.sh    - Ver logs del frontend"
echo "  ./logs-backend.sh     - Ver logs del backend"
echo "  ./deploy-test.sh      - Build de producción para pruebas"
echo ""
echo "📍 URLs IMPORTANTES:"
echo "  Frontend:    http://localhost:5175"
echo "  Backend:     http://localhost:5000"
echo "  Admin Panel: http://localhost:5175/admin/dashboard"
echo "  Credenciales: admin / admin"
echo ""
echo "🐛 SOLUCIÓN DE PROBLEMAS:"
echo "  Si hay errores, ejecuta: ./reset-project.sh"
echo "  Si los puertos están ocupados: ./stop-project.sh"
echo "  Para verificar estado: ./check-ports.sh"
echo ""
echo "=================================="
